version: '3.4'

services:

  stride-db-init:
    image: ghcr.io/hasadna/open-bus-stride-db/open-bus-stride-db:latest
    restart: "on-failure"
    environment:
      SQLALCHEMY_URL: "postgresql://postgres:123456@stride-db"
      PGPASSWORD: "123456"
      HOSTNAME: "stride-db"
      USER: "postgres"
      DB: "postgres"
      DB_RESTORE_FROM_URL: "${DB_RESTORE_FROM_URL}"
    depends_on:
      - stride-db

  stride-db:
    image: postgres:13
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
    volumes:
      - "stride-db:/var/lib/postgresql/data"

  stride-etl:
    image: ghcr.io/hasadna/open-bus-stride-etl/open-bus-stride-etl:latest
    restart: "no"
    environment:
      SQLALCHEMY_URL: "postgresql://postgres:123456@stride-db"
    depends_on:
      - stride-db

  gtfs-etl:
    image: ghcr.io/hasadna/open-bus-gtfs-etl/open-bus-gtfs-etl:latest
    restart: "no"
    environment:
      SQLALCHEMY_URL: "postgresql://postgres:123456@stride-db"
      GTFS_ETL_ROOT_ARCHIVES_FOLDER: "/var/gtfs-storage"
    depends_on:
      - stride-db
    volumes:
      - "gtfs-storage:/var/gtfs-storage"

  siri-requester:
    image: ghcr.io/hasadna/open-bus-siri-requester/open-bus-siri-requester:latest
    restart: unless-stopped
    environment:
      OPEN_BUS_SIRI_STORAGE_ROOTPATH: "/var/siri-storage"
      OPEN_BUS_MOT_KEY: "${OPEN_BUS_MOT_KEY}"
      OPEN_BUS_SSH_TUNNEL_PRIVATE_KEY_FILE: "/var/siri-requester-key/open-bus-ssh-tunnel-private-key-file"
      OPEN_BUS_SSH_TUNNEL_SERVER_IP: "${OPEN_BUS_SSH_TUNNEL_SERVER_IP}"
      OPEN_BUS_S3_ENDPOINT_URL: "${OPEN_BUS_S3_ENDPOINT_URL}"
      OPEN_BUS_S3_ACCESS_KEY_ID: "${OPEN_BUS_S3_ACCESS_KEY_ID}"
      OPEN_BUS_S3_SECRET_ACCESS_KEY: "${OPEN_BUS_S3_SECRET_ACCESS_KEY}"
      OPEN_BUS_S3_BUCKET: "${OPEN_BUS_S3_BUCKET}"
    volumes:
      - "siri-storage:/var/siri-storage"
      - ".data/siri-requester-key:/var/siri-requester-key"

  siri-requester-health:
    image: ghcr.io/hasadna/open-bus-siri-requester/open-bus-siri-requester:latest
    restart: unless-stopped
    entrypoint: [open-bus-siri-requester, health-daemon-start]
    environment:
      OPEN_BUS_SIRI_STORAGE_ROOTPATH: "/var/siri-storage"
    volumes:
      - "siri-storage:/var/siri-storage"

  siri-requester-nginx:
    image: ghcr.io/hasadna/open-bus-siri-requester/open-bus-siri-requester-nginx:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      SIRI_REQUESTER_HEALTH_URL: http://siri-requester-health:8081
    volumes:
      - "siri-storage:/srv"
    depends_on:
      - siri-requester-health

  siri-etl-process-new-snapshots:
    image: ghcr.io/hasadna/open-bus-siri-etl/open-bus-siri-etl:latest
    restart: unless-stopped
    command: [start-process-new-snapshots-daemon]
    environment:
      OPEN_BUS_SIRI_STORAGE_ROOTPATH: "/var/siri-storage"
      SQLALCHEMY_URL: "postgresql://postgres:123456@stride-db"
      DEBUG: "yes"
    volumes:
      - "siri-storage:/var/siri-storage"
    depends_on:
      - stride-db

  stride-api:
    image: ghcr.io/hasadna/open-bus-stride-api/open-bus-stride-api:latest
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      SQLALCHEMY_URL: "postgresql://postgres:123456@stride-db"
    depends_on:
      - stride-db

  airflow-db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "123456"
    volumes:
      - "airflow-db:/var/lib/postgresql/data"

  airflow-webserver:
    image: ghcr.io/hasadna/open-bus-pipelines/open-bus-pipelines:latest
    restart: unless-stopped
    build: .
    environment:
      OPEN_BUS_PIPELINES_AIRFLOW_INITIALIZE: "yes"
      OPEN_BUS_PIPELINES_AIRFLOW_ROLE: "webserver"
      OPEN_BUS_PIPELINES_AIRFLOW_ADMIN_PASSWORD: "123456"
    ports:
      - "8080:8080"
    volumes:
      - "airflow-home:/var/airflow"
    depends_on:
      - airflow-db

  airflow-scheduler:
    image: ghcr.io/hasadna/open-bus-pipelines/open-bus-pipelines:latest
    restart: unless-stopped
    build: .
    environment:
      OPEN_BUS_PIPELINES_DOWNLOAD_SIRI_SNAPSHOTS: "yes"
      OPEN_BUS_PIPELINES_AIRFLOW_ROLE: "scheduler"
      OPEN_BUS_SIRI_STORAGE_ROOTPATH: "/var/siri-storage"
      SQLALCHEMY_URL: "postgresql://postgres:123456@stride-db"
      DEBUG: "yes"
      GTFS_ETL_ROOT_ARCHIVES_FOLDER: "/var/gtfs-storage"
    volumes:
      - "airflow-home:/var/airflow"
      - "siri-storage:/var/siri-storage"
      - ".:/srv"
      - "gtfs-storage:/var/gtfs-storage"
    depends_on:
      - airflow-webserver
      - stride-db

volumes:
  stride-db:
  siri-storage:
  gtfs-storage:
  airflow-db:
  airflow-home:
